name: py36
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - numpy
    - matplotlib
    - jupyter
    - scikit-learn
    - scipy
    - seaborn
    - pandas
